name: watch_translator_flutter
description: Voice translation app optimized for Samsung Watch and Android Wear devices
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  shared_preferences: ^2.2.2
  vibration: ^1.8.4
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true